# Generated by Django 5.2.17 on 2026-08-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospecting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="analytics_signals",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="department",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="parsed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="seniority",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
